---
# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/ssd-pd
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd
