version: '3.5'

services:
  odm2_postgres_api:
    build: "."
    ports:
      - "127.0.0.1:8701:5000"
    volumes:
      - $HOME/stream-data/:/stream-data/
    depends_on:
      - timescale_odm2
      - db_init
    restart: always

  graphql:
    image: graphile/postgraphile
    ports:
      - "127.0.0.1:8702:5000"
    depends_on:
      - timescale_odm2
      - db_init
    restart: always
    command: --enhance-graphiql --owner-connection postgres://postgres:postgres@timescale_odm2:5432/niva_odm2 --connection postgres://niva_odm2_read_only_user:1oMPPgHu5TvhAkHYRUMIdaRSKZUjh6c5@timescale_odm2:5432/niva_odm2 --schema odm2 --watch --no-ignore-rbac

  timescale_odm2:
    # this version is the current timescaledb version running in production at the time of writing
    # Remember to change the image version in both tsb/docker-compose.yml and the nivacloud timescale deployment
    image: timescale/timescaledb-postgis:1.7.0-pg12
    ports:
      - "8700:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    # Please leave this commented volume since I use it all the time to get persistence while developing locally
    volumes:
      - $HOME/PycharmProjects/odm2_stuff/odm2_volume/postgres:/var/lib/postgresql/data

  db_init:
    build: "."
    command: python src/odm2_postgres_api/utils/db_initiate.py
    restart: on-failure
    depends_on:
      - timescale_odm2
